# Generated by Django 4.0.4 on 2022-04-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_wallet_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['owner']},
        ),
    ]
