# Generated by Django 4.0.4 on 2022-04-26 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_wallet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
